### ISSUE TITLE
ROS version?

### ISSUE THREAD

**Issue by zhengboom** [MingshanHe/Admittance-and-Application#3]
hello, can you tell me the version of ROS? when I `catkin_make` in ROS melodic, something is wrong...

**Comment by MingshanHe** [comment]
The simulation branch is tested by Ubuntu16.04 and Ubuntu18.04. And there is only one change between the two versions.
The real-hardware branch is tested by Ubuntu 20.04. Hope this information can help you. Or you can paste your build error.

**Comment by zhengboom** [comment]
Thank you so much!





------------------ Original ------------------
From: Mingshan-Beal ***@***.***&gt;
Date: Tue,Feb 15,2022 1:25 PM
To: MingshanHe/Admittance-and-Application ***@***.***&gt;
Cc: zhengboom ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [MingshanHe/Admittance-and-Application] ROS version? (Issue #3)





 
The simulation branch is tested by Ubuntu16.04 and Ubuntu18.04. And there is only one change between the two versions.
 The real-hardware branch is tested by Ubuntu 20.04. Hope this information can help you. Or you can paste your build error.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
