### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by zhengboom** [MingshanHe/Admittance-and-Application#4]
hello, can you tell me where can I find the 'universal_robot_databag'? Thank you for your help.
![图片](https://user-images.githubusercontent.com/80376379/154019803-2134a595-58e8-4199-87d8-a72003f99036.png)

**Comment by MingshanHe** [comment]
I have used rospackage `databag`  to record the data for test. I will fig this bug in launch file.

**Comment by MingshanHe** [comment]
OK. I have fixed it and I hope you can git clone it again and build it.

**Comment by zhengboom** [comment]
OK, I get it, thanks a lot !
