### ISSUE TITLE
Problems connecting to a real robot

### ISSUE THREAD

**Issue by MZJR** [MingshanHe/Admittance-and-Application#5]
I tried incorporating the real-robot version into my own UR5e startup file.
But running have an error：
`[ERROR] [1645000038.861793476]: Could not load controller 'cartesian_velocity_controller_sim' because controller type 'cartesian_controller/CartesianVelocityController' does not exist.
`
It doesn't seem to recognize your custom controller type, how can I do for this？

**Comment by MZJR** [comment]
When I compile the **cartesian_velocity_controller** package independently,it worked.

**Comment by MingshanHe** [comment]
Thanks for your issue, I think this will help other people for running this code.
