### ISSUE TITLE
 Could not load controller 'cartesian_velocity_contraller_sim' because the type was not specified. 

### ISSUE THREAD

**Issue by jz068** [MingshanHe/Admittance-and-Application#7]
[ERROR] [1647413655.498812691, 0.289000000]: Could not load controller 'cartesian_velocity_contraller_sim' because the type was not specified. Did you load the controller configuration on the parameter server (namespace: '/cartesian_velocity_contraller_sim')?
Error when loading 'cartesian_velocity_contraller_sim'
[ERROR] [1647413655.501064126, 0.291000000]: Could not start controller with name 'cartesian_velocity_contraller_sim' because no controller with this name exists

hi, the erroe was occured when i run 'roslaunch ur_e_gazebo ur5e.launch controller:=cartesian_velocity_controller_sim' in ros.

**Comment by jz068** [comment]
I compiled the folder（cartesian_velocity_contraller） independently and still reported an error. My ubuntu version is 18.04.

**Comment by MingshanHe** [comment]
I have tested in Ubuntu 16.04, Ubuntu18.04 and Ubuntu20.04. I recommend you source the workspace or reboot the computer. You have compiled the `cartesian_velocity_controller` successfully, and the workspace may not identify the controller. So please try to source the workspace.
